name: MSD 
on:
  push: 
jobs:
  build:
    runs-on: macos-latest 
    steps:
      - name: Checkout v1
        uses: actions/checkout@v1
      - name: make executable
        run: c++ -std=c++11 hw2_expression/hw2_expression/*.cpp -o prog
      - name: run test 
        run: ./prog --test
