name: MSD 
on:
  push: 
jobs:
  build:
    runs-on: macos-latest 
    steps:
      - name: Checkout v1
        uses: actions/checkout@v1
      - name: cd project file
        run: cd hw2_expression/hw2_expression/
      - name: make executable
        run: c++ -std=c++11 main.cpp expr.cpp tests.cpp cmdline.cpp -o prog
      - name: run test 
        run: ./prog --test
