name: MSD 
on:
  push: 
jobs:
  build:
    runs-on: macos-latest 
    steps:
      - name: Checkout v1
        uses: actions/checkout@v1
      - name: make executable
        run: cd hw2_expression/hw2_expression && make program
      - name: run test 
        run: cd hw2_expression/hw2_expression && make test
